version: '3.8'

services:

    devinlove:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: devinlove:0.1
        restart: unless-stopped
        container_name: devinlove
        env_file:
            - ./environment/dev.django.env
            - ./environment/dev.db.env
        expose:
            - "8000"
        volumes:
            - static:/app/static_files
            - ./templates:/app/templates
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - app

    app:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            # These ports are in format <host-port>:<container-port>
            - '80:80' # Public HTTP Port
            - '443:443' # Public HTTPS Port
            - '81:81' # Admin Web Port
            # Add any other Stream port you want to expose
            # - '21:21' # FTP
        environment:
            DB_MYSQL_HOST: "db"
            DB_MYSQL_PORT: 3306
            DB_MYSQL_USER: "npm"
            DB_MYSQL_PASSWORD: "npm"
            DB_MYSQL_NAME: "npm"
            # Uncomment this if IPv6 is not enabled on your host
            # DISABLE_IPV6: 'true'
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
            - static:/app/static_files
        depends_on:
            - db

    db:
        image: 'jc21/mariadb-aria:latest'
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 'npm'
            MYSQL_DATABASE: 'npm'
            MYSQL_USER: 'npm'
            MYSQL_PASSWORD: 'npm'
        volumes:
            - ./data/mysql:/var/lib/mysql

volumes:
    static: