# Generated by Django 3.2.7 on 2021-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('B', 'Banido'), ('E', 'Em espera')], default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='declaration',
            name='declaration',
            field=models.CharField(help_text='Declaração bonitona para o seu s2', max_length=250, verbose_name='Declaração'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='title',
            field=models.CharField(help_text='Título bonitão', max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='url_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
