# Generated by Django 3.2.7 on 2021-09-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url_slug', models.SlugField(max_length=100)),
                ('declaration', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Declaração',
                'verbose_name_plural': 'Declarações',
            },
        ),
    ]
